"""
Scrapes a FACT-LINK Vietnam category into the staging_factlink Postgres table.

Usage:
    python scrapers/factlink_scraper.py --category-label "Rubber molding"
    python scrapers/factlink_scraper.py --category-id 044

--category-label resolves the category id via data/factlink_categories.json
(generated by discover_categories.py). Rows are upserted keyed on
(profile_id, source_category_id): the same company can legitimately appear
under multiple categories, so each category listing is its own row.

Site notes (learned by probing the live site):
- FACT-LINK Vietnam lives at fact-link.com.vn (NOT fact-link.com, which is
  the Thailand site).
- Category listing pages are plain GETs: search_category.php?id=012&start=N,
  30 companies per page.
- Profile pages (mem_profile.php) refuse to render (infinite meta-refresh)
  unless the request carries a session cookie from a prior listing-page GET
  AND a Referer header pointing at a search_category.php URL. We satisfy
  both by using a requests.Session and always sending a Referer.
- Field labels on profile pages are not fixed across companies (e.g.
  "Address" vs "Head Office Add" vs "Factory address" vs branch names, and
  the "contact person" row uses the person's own name as the label). The
  parser below does a best-effort keyword-based mapping into structured
  columns and always keeps the full label/value list in `raw` for later
  re-parsing/enrichment.
"""

import argparse
import json
import logging
import os
import random
import re
import sys
import time
from urllib.parse import urljoin

import psycopg2
import psycopg2.extras
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv

# Category labels and scraped company data (addresses, names) can contain
# non-ASCII text (fullwidth punctuation, Vietnamese/Japanese); Windows'
# default console/redirect encoding (cp1252) can't print those, so force UTF-8.
sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")

BASE_URL = "https://www.fact-link.com.vn/"
SOURCE_SITE = "fact-link-vietnam"
PAGE_SIZE = 30
LANG_PREFERENCE = ["en", "vn", "jp"]
MIN_DELAY_SECONDS = 2.0
MAX_DELAY_SECONDS = 3.0
RAW_HTML_DIR = os.path.join("data", "factlink_raw")
CATEGORIES_PATH = os.path.join("data", "factlink_categories.json")
SUMMARY_PATH = os.path.join("data", "factlink_last_run_summary.json")
USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger("factlink_scraper")

# Labels matched (case-insensitive substring) straight into a single column.
# Checked in order; first match wins.
DIRECT_FIELD_PATTERNS = [
    (re.compile(r"^company name$", re.I), "company_name"),
    (re.compile(r"business description", re.I), "business_description"),
    (re.compile(r"^produce", re.I), "produce_list"),
    (re.compile(r"establish date", re.I), "establish_date"),
    (re.compile(r"employee", re.I), "_employee_raw"),
    (re.compile(r"certification", re.I), "certifications"),
    (re.compile(r"capital", re.I), "capital_vnd"),
    (re.compile(r"parent company", re.I), "parent_company"),
    (re.compile(r"shareholder", re.I), "shareholder_name"),
]

EMAIL_RE = re.compile(r"[\w.+-]+@[\w-]+\.[\w.-]+")
PHONE_RE = re.compile(r"(\+?\d[\d\-\s]{6,}\d)")


def strip_nul_bytes(value):
    """Postgres TEXT/JSONB can never store raw NUL (0x00) bytes; some FACT-LINK
    pages contain them (garbled encoding, e.g. a '~' mangled to NUL inside a
    numeric range like "0.25\\x00.4"). Recursively strip them so a single
    dirty field can't fail the whole upsert."""
    if isinstance(value, str):
        return value.replace("\x00", "")
    if isinstance(value, dict):
        return {k: strip_nul_bytes(v) for k, v in value.items()}
    if isinstance(value, list):
        return [strip_nul_bytes(v) for v in value]
    return value


def sleep_politely():
    time.sleep(random.uniform(MIN_DELAY_SECONDS, MAX_DELAY_SECONDS))


def parse_listing(html):
    """Return {profile_id: {lang: page_id}} for every profile link on a listing page."""
    soup = BeautifulSoup(html, "html.parser")
    companies = {}
    for a in soup.find_all("a", href=True):
        m = re.match(r"mem_profile\.php\?id=(\d+)&page=(\d+)&lang=(\w+)", a["href"])
        if not m:
            continue
        profile_id, page_id, lang = m.groups()
        companies.setdefault(profile_id, {})[lang] = page_id
    return companies


def pick_lang(lang_pages):
    for lang in LANG_PREFERENCE:
        if lang in lang_pages:
            return lang, lang_pages[lang]
    lang = next(iter(lang_pages))
    return lang, lang_pages[lang]


def parse_category_label(html):
    """Best-effort extraction of the human-readable category name from a listing page."""
    m = re.search(r'<meta name="keywords" content="([^"]+)"', html)
    if m:
        return m.group(1).strip()
    m = re.search(r"<title>([^<|]+)", html)
    if m:
        return m.group(1).strip()
    return None


def discover_all_companies(session, category_id):
    """Paginate the category listing until a page contributes no new profile ids.

    Returns (companies, category_label) where category_label is parsed off the
    first listing page (falls back to None if it can't be found).
    """
    all_companies = {}
    category_label = None
    start = 0
    while True:
        url = urljoin(BASE_URL, f"search_category.php?id={category_id}&start={start}")
        resp = session.get(url, timeout=30)
        resp.raise_for_status()
        if category_label is None:
            category_label = parse_category_label(resp.text)
        page_companies = parse_listing(resp.text)
        new_ids = set(page_companies) - set(all_companies)
        log.info("Listing start=%d: %d companies (%d new)", start, len(page_companies), len(new_ids))
        if not new_ids:
            break
        all_companies.update(page_companies)
        start += PAGE_SIZE
        sleep_politely()
    return all_companies, category_label


def fetch_profile_html(session, profile_id, page_id, lang, referer_url, max_retries=2):
    """Fetch a profile page, retrying on the redirect-loop anti-scrape guard.

    The very first profile request right after a fresh listing-page fetch
    reliably hits this redirect loop -- the site's server-side session state
    needs a brief moment to settle before it'll honor a profile request. A
    short retry clears it almost every time; later requests in the same
    session don't need this.
    """
    url = urljoin(
        BASE_URL,
        f"mem_profile.php?id={profile_id}&page={page_id}&lang={lang}",
    )
    for attempt in range(max_retries + 1):
        resp = session.get(url, headers={"Referer": referer_url}, timeout=30)
        resp.raise_for_status()
        if "http-equiv = \"refresh\"" in resp.text and len(resp.text) < 500:
            if attempt < max_retries:
                log.warning(
                    "profile %s redirect-looped, retrying (attempt %d/%d)...",
                    profile_id, attempt + 1, max_retries,
                )
                time.sleep(random.uniform(MIN_DELAY_SECONDS, MAX_DELAY_SECONDS))
                continue
            raise RuntimeError(f"profile {profile_id} redirect-looped (session/referer rejected)")
        return url, resp.text


def parse_profile(html):
    soup = BeautifulSoup(html, "html.parser")
    data = {}
    raw_fields = []
    office_parts, factory_parts, phone_parts, email_parts = [], [], [], []
    representative_name = None
    fallback_contact_name = None
    fallback_contact_email = None
    fallback_contact_phone = None

    # The label color varies by company/template (#0066CC, #CC0000, #336600, ...),
    # so match any <font color="..."><strong>Label</strong></font> cell.
    for font in soup.find_all("font", attrs={"color": True}):
        strong = font.find("strong")
        if not strong:
            continue
        label = strong.get_text(strip=True)
        if not label or label.lower() == "contact":
            continue
        tr = font.find_parent("tr")
        if not tr:
            continue
        tds = tr.find_all("td", recursive=False)
        if len(tds) < 2:
            continue
        value = tds[-1].get_text(separator=" ", strip=True)
        value = re.sub(r"\s+", " ", value).strip()
        if not value:
            continue

        raw_fields.append({"label": label, "value": value})

        matched_field = None
        for pattern, field in DIRECT_FIELD_PATTERNS:
            if pattern.search(label):
                matched_field = field
                break
        if matched_field:
            data[matched_field] = value
            continue

        low = label.lower()
        if low == "website":
            data["website"] = value
        elif "tel" in low or "phone" in low or "fax" in low:
            phone_parts.append(value)
        elif "factory" in low:
            factory_parts.append(value)
        elif "office" in low or low == "address":
            office_parts.append(value)
        elif "email" in low or "e-mail" in low:
            email_parts.append(value)
        elif low == "representative name":
            representative_name = value
        else:
            email_match = EMAIL_RE.search(value)
            if email_match and fallback_contact_email is None:
                fallback_contact_name = label
                fallback_contact_email = email_match.group(0)
                phone_match = PHONE_RE.search(value)
                if phone_match:
                    fallback_contact_phone = phone_match.group(0).strip()

    if office_parts:
        data["office_address"] = "\n".join(dict.fromkeys(office_parts))
    if factory_parts:
        data["factory_address"] = "\n".join(dict.fromkeys(factory_parts))
    if phone_parts:
        data["phone"] = phone_parts[0]
    elif fallback_contact_phone:
        data["phone"] = fallback_contact_phone

    all_emails = []
    for v in email_parts:
        all_emails.extend(EMAIL_RE.findall(v))
    if all_emails:
        data["contact_email"] = all_emails[0]
    elif fallback_contact_email:
        data["contact_email"] = fallback_contact_email

    if fallback_contact_name:
        data["contact_name"] = fallback_contact_name
    elif representative_name:
        data["contact_name"] = representative_name

    if "_employee_raw" in data:
        m = re.search(r"\d+", data["_employee_raw"])
        if m:
            data["employee_count"] = int(m.group(0))
        del data["_employee_raw"]

    data["raw"] = {"fields": raw_fields}
    return strip_nul_bytes(data)


UPSERT_SQL = """
INSERT INTO staging_factlink (
    profile_id, company_name, website, phone, contact_name, contact_email,
    office_address, factory_address, business_description, produce_list,
    establish_date, employee_count, certifications, capital_vnd,
    shareholder_name, parent_company, raw_html_path, raw,
    source_site, source_category_id, source_category_label
) VALUES (
    %(profile_id)s, %(company_name)s, %(website)s, %(phone)s, %(contact_name)s, %(contact_email)s,
    %(office_address)s, %(factory_address)s, %(business_description)s, %(produce_list)s,
    %(establish_date)s, %(employee_count)s, %(certifications)s, %(capital_vnd)s,
    %(shareholder_name)s, %(parent_company)s, %(raw_html_path)s, %(raw)s,
    %(source_site)s, %(source_category_id)s, %(source_category_label)s
)
ON CONFLICT (profile_id, source_category_id) DO UPDATE SET
    company_name = EXCLUDED.company_name,
    website = EXCLUDED.website,
    phone = EXCLUDED.phone,
    contact_name = EXCLUDED.contact_name,
    contact_email = EXCLUDED.contact_email,
    office_address = EXCLUDED.office_address,
    factory_address = EXCLUDED.factory_address,
    business_description = EXCLUDED.business_description,
    produce_list = EXCLUDED.produce_list,
    establish_date = EXCLUDED.establish_date,
    employee_count = EXCLUDED.employee_count,
    certifications = EXCLUDED.certifications,
    capital_vnd = EXCLUDED.capital_vnd,
    shareholder_name = EXCLUDED.shareholder_name,
    parent_company = EXCLUDED.parent_company,
    raw_html_path = EXCLUDED.raw_html_path,
    raw = EXCLUDED.raw,
    source_site = EXCLUDED.source_site,
    source_category_label = EXCLUDED.source_category_label,
    scraped_at = NOW()
RETURNING (xmax = 0) AS inserted;
"""


def upsert_company(conn, record):
    """Insert or update the row keyed on (profile_id, source_category_id).

    Returns True if a new row was inserted, False if an existing row was updated
    (the `xmax = 0` trick: xmax is unset on a fresh insert, set on the update path
    of an ON CONFLICT DO UPDATE).
    """
    row = {
        "profile_id": record["profile_id"],
        "company_name": record.get("company_name"),
        "website": record.get("website"),
        "phone": record.get("phone"),
        "contact_name": record.get("contact_name"),
        "contact_email": record.get("contact_email"),
        "office_address": record.get("office_address"),
        "factory_address": record.get("factory_address"),
        "business_description": record.get("business_description"),
        "produce_list": record.get("produce_list"),
        "establish_date": record.get("establish_date"),
        "employee_count": record.get("employee_count"),
        "certifications": record.get("certifications"),
        "capital_vnd": record.get("capital_vnd"),
        "shareholder_name": record.get("shareholder_name"),
        "parent_company": record.get("parent_company"),
        "raw_html_path": record.get("raw_html_path"),
        "raw": psycopg2.extras.Json(record.get("raw") or {}),
        "source_site": record.get("source_site"),
        "source_category_id": record.get("source_category_id"),
        "source_category_label": record.get("source_category_label"),
    }
    with conn.cursor() as cur:
        cur.execute(UPSERT_SQL, row)
        inserted = cur.fetchone()[0]
    conn.commit()
    return inserted


def load_categories():
    if not os.path.exists(CATEGORIES_PATH):
        raise SystemExit(
            f"{CATEGORIES_PATH} not found. Run `python scrapers/discover_categories.py` first."
        )
    with open(CATEGORIES_PATH, encoding="utf-8") as f:
        return json.load(f)


def resolve_category(args):
    """Return (category_id, category_label). category_label is the exact string
    the caller asked for when --category-label was used, or None when
    --category-id was used directly (in which case it gets auto-parsed off the
    listing page instead, same as before)."""
    if args.category_id:
        return args.category_id, None
    categories = load_categories()
    label = args.category_label
    if label not in categories:
        available = "\n".join(f"  - {l}" for l in sorted(categories))
        raise SystemExit(
            f"Unknown category label {label!r}.\n"
            f"Run `python scrapers/discover_categories.py` to refresh {CATEGORIES_PATH}, "
            f"or pick one of:\n{available}"
        )
    return categories[label], label


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--category-label",
        help="Category label to look up in data/factlink_categories.json, e.g. 'Rubber molding'.",
    )
    group.add_argument(
        "--category-id",
        help="FACT-LINK category code directly, e.g. '012' (bypasses the label lookup).",
    )
    return parser.parse_args()


def main():
    load_dotenv()
    args = parse_args()
    category_id, resolved_label = resolve_category(args)
    database_url = os.environ["DATABASE_URL"]
    os.makedirs(RAW_HTML_DIR, exist_ok=True)

    session = requests.Session()
    session.headers.update({"User-Agent": USER_AGENT})

    conn = psycopg2.connect(database_url)

    stats = {
        "scraped": 0,
        "inserted": 0,
        "updated": 0,
        "failed": 0,
        "with_website": 0,
        "with_certifications": 0,
        "with_factory_address": 0,
    }

    try:
        log.info("Discovering companies in category %s ...", category_id)
        companies, parsed_label = discover_all_companies(session, category_id)
        category_label = resolved_label or parsed_label
        log.info(
            "Found %d companies with a viewable profile page. Category label: %r",
            len(companies), category_label,
        )

        referer_url = urljoin(BASE_URL, f"search_category.php?id={category_id}&start=0")

        for i, (profile_id, lang_pages) in enumerate(companies.items(), start=1):
            lang, page_id = pick_lang(lang_pages)
            try:
                log.info("[%d/%d] Fetching profile %s (lang=%s)", i, len(companies), profile_id, lang)
                url, html = fetch_profile_html(session, profile_id, page_id, lang, referer_url)

                raw_html_path = os.path.join(RAW_HTML_DIR, f"profile_{profile_id}.html")
                with open(raw_html_path, "w", encoding="utf-8") as f:
                    f.write(html)

                record = parse_profile(html)
                record["profile_id"] = profile_id
                record["raw_html_path"] = raw_html_path
                record["raw"]["meta"] = {"lang": lang, "url": url}
                record["source_site"] = SOURCE_SITE
                record["source_category_id"] = category_id
                record["source_category_label"] = category_label

                inserted = upsert_company(conn, record)

                stats["scraped"] += 1
                stats["inserted" if inserted else "updated"] += 1
                if record.get("website"):
                    stats["with_website"] += 1
                if record.get("certifications"):
                    stats["with_certifications"] += 1
                if record.get("factory_address"):
                    stats["with_factory_address"] += 1

            except Exception as exc:
                stats["failed"] += 1
                log.error("Failed on profile %s: %s", profile_id, exc)

            sleep_politely()

    finally:
        conn.close()

    summary = {
        "category_id": category_id,
        "category_label": category_label,
        "companies_discovered": len(companies),
        **stats,
    }
    os.makedirs(os.path.dirname(SUMMARY_PATH), exist_ok=True)
    with open(SUMMARY_PATH, "w", encoding="utf-8") as f:
        json.dump(summary, f, ensure_ascii=False, indent=2)

    print(f"\n=== FACT-LINK Vietnam scrape summary: {category_label} (id={category_id}) ===")
    print(f"Companies discovered:        {summary['companies_discovered']}")
    print(f"Successfully scraped:        {stats['scraped']}")
    print(f"  New rows inserted:         {stats['inserted']}")
    print(f"  Existing rows updated:     {stats['updated']}")
    print(f"Failed:                      {stats['failed']}")
    print(f"With website:                {stats['with_website']}")
    print(f"With certifications:         {stats['with_certifications']}")
    print(f"With factory address:        {stats['with_factory_address']}")


if __name__ == "__main__":
    main()
